config/routes.rb
Rails.application.routes.draw do
  # admin各種resources
  namespace :admin do
    resources :users, only: [:show, :edit, :update]
  end
  
  
  
  
  # ルートパス。ユーザー用なのでpublic
  root to: 'public/homes#top'
  
  # 管理者用のルート。(publicに当てているのでルートパスではない)
  get '/admin' => 'admin/homes#top'
  
  
  
  
  # ゲストログイン用ルーティング
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  get 'about' => 'public/homes#about'




  # ユーザー用Devise関連
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }




  # 管理者用Devise関連
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  
  
  
  # 各publicルーティング
  scope module: :public do
    # get 'users/mypage' => 'users#show', as: 'mypage'
    # get 'users/information' => 'users#edit', as: 'user_edit'
    # patch 'users/information' => 'users#update', as: 'user_update'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal', as: 'withdrawal'


    # 各種resources
    resources :users, only: [:show, :edit, :update] do
      member do
        get :favorites
      end
      collection do
        get :search
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :travels, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]  # 「いいね」は「投稿(travel)」に対して行われるので、いいねのルーティングは投稿(:travels)に結びつく、親子関係となる(ネスト)
      resources :comments, only: [:create, :destroy]  # コメントも「いいね」同様、投稿(travel)に対して行われるので、投稿(:travels)に結びつく。よってネストとなる。
      collection do
        get :search
      end
    end
  end
  # namespace :admin do
  #   root to: 'homes#top'
  # end

  # devise_for :admins
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :move_to_signed_in
  def top
    @users = User.all  # 全登録ユーザーを取得
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h1>登録ユーザー一覧</h1>
  </div>
  <div class="row">
      <table class="table table-hover text-center top-table">
        <thead>
          <tr>
            <th style="width:50px;">ID</th>
            <th style="width:228px;">ユーザー名</th>
            <th style="width:100px;">投稿数</th>
            <th style="width:100px;">フォロー数</th>
            <th style="width:100px;">フォロワー数</th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>  <!--admin/homes#topにて定義の@usersを使用-->
          <tr>
            <td style="line-height:101px;"><%= user.id %></td>
            <td>
              <%= link_to admin_user_path(user.id) do  %>  <!--ユーザー詳細情報ページへのリンク-->
                <%= image_tag user.get_profile_image(100, 100) %>
                <%= user.nickname %>
              <% end %>
            </td>
            <td><%= user.travels.count %></td>  <!--userに紐づく、全てのtravels(アソシエーションを結んでいる)を取得-->
            <td><%= user.following_user.count %></td>
            <td><%= user.follower_user.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>