config/routes.rb
Rails.application.routes.draw do
  # admin各種resources
  namespace :admin do
    resources :users, only: [:show, :edit, :update]
  end
  
  
  
  
  # ルートパス。ユーザー用なのでpublic
  root to: 'public/homes#top'
  
  # 管理者用のルート。(publicに当てているのでルートパスではない)
  get '/admin' => 'admin/homes#top'
  
  
  
  
  # ゲストログイン用ルーティング
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  get 'about' => 'public/homes#about'




  # ユーザー用Devise関連
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }




  # 管理者用Devise関連
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  
  
  
  # 各publicルーティング
  scope module: :public do
    # get 'users/mypage' => 'users#show', as: 'mypage'
    # get 'users/information' => 'users#edit', as: 'user_edit'
    # patch 'users/information' => 'users#update', as: 'user_update'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal', as: 'withdrawal'


    # 各種resources
    resources :users, only: [:show, :edit, :update] do
      member do
        get :favorites
      end
      collection do
        get :search
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :travels, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]  # 「いいね」は「投稿(travel)」に対して行われるので、いいねのルーティングは投稿(:travels)に結びつく、親子関係となる(ネスト)
      resources :comments, only: [:create, :destroy]  # コメントも「いいね」同様、投稿(travel)に対して行われるので、投稿(:travels)に結びつく。よってネストとなる。
      collection do
        get :search
      end
    end
  end
  # namespace :admin do
  #   root to: 'homes#top'
  # end

  # devise_for :admins
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :travels, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # フォロー機能のアソシエーション
  # フォローした、されたの関係
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  # フォローしている人の取得（Userのfollowerから見た関係）
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  # フォローされている人の取得（Userのfollowedから見た関係）

  # フォロー一覧やフォロワー一覧でユーザーを取得、表示するためのアソシエーション
  has_many :following_user, through: :follower, source: :followed  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower  # 自分をフォローしている人（自分がフォローされている人）



  # フォローしたときの処理
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているかの判定
  def following?(user)
    following_user.include?(user)
  end


  # ゲストログイン用ユーザーデータ(public/sessions#guest_sign_inにて使用)
  def self.guest  # クラスメソッド。
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = 'ゲスト'
      user.last_name = 'ゲスト'
      user.first_name = '太郎'
      user.last_name_kana = 'ゲスト'
      user.first_name_kana = 'タロウ'
    end
  end




  # プロフィール画像を:profile_imageにて保持
  has_one_attached :profile_image


  # プロフィール画像の取得(丸く表示する為に正方形に切り出す)
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :move_to_signed_in
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # byebug
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to admin_user_path(@user)
  end


  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1>
      <%= @user.nickname %> さんの会員情報編集画面
    </h1>
  </div>

  <div class="row">
    <div>
      この画面では登録ユーザーの退会情報の編集ができます。
      不適切なユーザーは管理者権限で強制退会が可能です。
    </div>
  </div>

  <div class="row">
    <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= @user.nickname %></td>
        </tr>
        <tr>
          <th>登録名（姓）</th>
          <td><%= @user.last_name %></td>
          <th>（名）</th>
          <td><%= @user.first_name %></td>
        </tr>
        <tr>
          <th>登録名（セイ）</th>
          <td><%= @user.last_name_kana %></td>
          <th>（メイ）</th>
          <td><%= @user.first_name_kana %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>退会フラグ</th>
          <td>
            <%= f.radio_button :is_deleted, "false" %>
            <%= f.label :is_deleted_false, "有効" %>

            <%= f.radio_button :is_deleted, "true" %>
            <%= f.label :is_deleted_true, "退会" %>
          </td>
        </tr>
      </table>
      <%= f.submit "更新する", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <h1>
      <%= @user.nickname %> さんの会員情報詳細画面
    </h1>
  </div>

  <div class="row justify-content-center">
    <!--プロフィール画像(必要であれば)-->
    <%= image_tag @user.get_profile_image(100, 100) %>
  </div>

  <div class="row justify-content-center">
    <div>
    <table class="table table-borderless">
      <tr>
        <th>ユーザーID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>ニックネーム</th>
        <td><%= @user.nickname %></td>
      </tr>
      <tr>
        <th>登録名（姓）</th>
        <td><%= @user.last_name %></td>
        <th>（名）</th>
        <td><%= @user.first_name %></td>
      </tr>
      <tr>
        <th>登録名（セイ）</th>
        <td><%= @user.last_name_kana %></td>
        <th>（メイ）</th>
        <td><%= @user.first_name_kana %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @user.is_deleted %>
            <span class="text-secondary">退会</span>
          <% else %>
            <span class="text-success">有効</span>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="text-center">
      <%= link_to "編集する", edit_admin_user_path, class: "btn btn-primary" %>
    </div>

    </div>
  </div>
</div>